services:
  - type: web
    name: shopeasy-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run render-start
    rootDir: shopeasy-clean/backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://fgdscohjkkpluhtlruau.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZHNjb2hqa2twbHVodGxydWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDI1MzEsImV4cCI6MjA3MjMxODUzMX0.P59uwU00Tu7WIMC85k8uoURIysBZI55g8HN9hwtK3jU
      - key: TWILIO_ACCOUNT_SID
        value: your_twilio_account_sid_here
      - key: TWILIO_AUTH_TOKEN
        value: your_twilio_auth_token_here
      - key: TWILIO_VERIFY_SERVICE_SID
        value: your_twilio_verify_service_sid_here
    healthCheckPath: /health
    autoDeploy: true
